### PR TITLE
Feature: Select the hub with the shortest response time among the resolved hubs

### PR DESCRIPTION
**Pull request by jiachengzhang1**

### CODE REVIEW

**Comment by chavoosh** [comment]
Looks good. Did you test it?

**Comment by jiachengzhang1** [comment]
> Looks good. Did you test it?

Yes, I just test it again, it works.
Test cases:
   1, all hubs work
   2, two hubs work
   3, three hubs work
   4, first try: all hubs down, retry: work (manually change the hub list for retry)
   5, first try: all hubs down, retry 4 times (in this case, no hub list change)

Those are the test cases I covered, let me know if there are more cases I can add to it.

Note:
If everything is good for `app.js` so far, I'm going to apply the update to `app_test.js` for `online-test`.

**Comment by chavoosh** [comment]
Yes, please go ahead and update `app-test.js` and push a commit.

**Comment by jiachengzhang1** [comment]
> Yes, please go ahead and update `app-test.js` and push a commit.

Done!

**Pull request merged**
